server:
  port: 8000
spring:
  application:
    name: cloud-order-hystrix-order
eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true

    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone : http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone : http://eureka7001.com:7001/eureka
  instance:
    instance-id: order8000
    prefer-ip-address: true
#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
  # feign 日志以什么级别监控那个接口
  #  com.xlc.springcloud.service.PaymentFeignService: debug
    com.xlc.springcloud.service.PaymentFeignService: debug
feign:
  hystrix:
    enabled: true
