server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: http:192.168.32.16:1111
management:
  endpoint:
    web:
      exposure:
        include: '*'  #监控
