server:
  port: 8002

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.xlc.springcloud.entities
spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
  application:
    name: cloud-prvide-srvice


eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true

    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone : http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone : http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true #访问路径可以显示IP地址









